CREATE TABLE manutencoes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    moto_id BIGINT NOT NULL,
    descricao VARCHAR(255),
    data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fim TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    ativa TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT fk_manutencao_moto FOREIGN KEY (moto_id) REFERENCES motos(id) ON DELETE CASCADE
);